modLoader = "javafml"
loaderVersion = "[44,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/DavidQF555/Form1040/issues"
[[mods]]
modId = "f1040"
version = "${file.jarVersion}"
displayName = "Form 1040"
displayURL = "https://github.com/DavidQF555/Form1040"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds taxes.'
[[dependencies.f1040]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.f1040]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
